spring:
  application:
    name: UserAuthService
  datasource:
    url: jdbc:mysql://localhost:3306/user_auth_service
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/